name: Upload Website

on:
  push:
    branches:
      - main

jobs:
    upload:
        runs-on: ubuntu-latest
        # timeout-minutes: 10
        steps:
          - name: Set AWS Credentials
            uses: actions/checkout@main
            uses: jakejarvis/s3-sync-action@main
            with:
              args: --acl public-read --follow-symlinks --delete
            env:
              aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              # aws-s3-bucket: ${{ secrets.AWS_S3BUCKET_NAME }}
              aws-region: ${{ secrets.AWS_REGION }}
          - name: Deploy to S3
            run: aws s3 sync . s3://sleslie23 --delete